# Generated by Django 5.2.11 on 2026-03-01 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myflix', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_stream', models.CharField(max_length=10)),
                ('descricao', models.TextField(max_length=255)),
                ('categoria', models.CharField(choices=[('F', 'Filmes'), ('S', 'Série'), ('D', 'Documentário')], default='F', max_length=1)),
            ],
        ),
    ]
