# Generated by Django 5.2.11 on 2026-03-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myflix', '0002_stream'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stream',
            old_name='codigo_stream',
            new_name='codigo',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='numero_telefone',
            new_name='celular',
        ),
        migrations.AlterField(
            model_name='stream',
            name='categoria',
            field=models.CharField(choices=[('F', 'Filme'), ('S', 'Série'), ('D', 'Documentário')], default='F', max_length=1),
        ),
        migrations.AlterField(
            model_name='stream',
            name='descricao',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
