# Generated by Django 5.2.11 on 2026-03-01 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myflix', '0003_rename_codigo_stream_stream_codigo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='lista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myflix.stream')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myflix.user')),
            ],
        ),
    ]
